### ISSUE TITLE
Malloc used for i_block

### ISSUE THREAD

**Issue by AmusedNetwork** [gabemaiberger/libpqc#2]
Hi Gabe,

Is there a reason you are using malloc in the r3d_decrypt_xex, and r3d_encrypt_xex functions (instead of calloc)? It seems like it would cause issues where malloc returns uninitialized memory. It's possible I am misunderstanding the code but doesn't this mean that encrypt and decrypt could have different values for the `i_block` and therefore also the `x_block`?

https://github.com/gabemaiberger/libpqc/blob/069f00d362b0854b5097321757e37b4e3041a205/r3d_modes.c#L217

Thanks for your help.

**Comment by gabemaiberger** [comment]
The i_block and the x_block are supposed to be different. The x_block is the encrypted i_block. You are correct that I should probably be using calloc instead of malloc. Please correct me if I am misunderstanding what you are saying.

**Comment by AmusedNetwork** [comment]
I was just checking if you should be using malloc or calloc - the memory that malloc allocates isn't cleared, so could have random data (causing the initial encryption to be different for the decryption step). I just wasn't too sure if I had misunderstood the program. 

Thanks

**Comment by gabemaiberger** [comment]
I had commented out free() because it was causing crashes. I need to fix memory handling.

**Comment by gabemaiberger** [comment]
I replaced malloc with calloc for the i_block in the appropriate XEX functions.
